{% set name = 'nictools' %}
{% set version = '1.1.5' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    summary: |
        Python tools for NICMOS data

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - numpy {{ numpy }}
    - scipy
    - stsci.tools
    - stsci.imagestats
    - setuptools
    - setuptools_scm
    - python {{ python }}
    run:
    - astropy >=1.1
    - numpy
    - scipy
    - stsci.tools
    - stsci.imagestats
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - nictools
