{% set name = 'drizzlepac' %}
{% set version = '2.1.6' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: AstroDrizzle for HST images

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - fitsblender
    - nictools
    - numpy
    - scipy
    - stsci.convolve
    - stsci.distutils
    - stsci.image
    - stsci.imagemanip
    - stsci.imagestats
    - stsci.ndimage
    - stsci.skypac
    - stsci.sphere
    - stsci.stimage
    - stwcs
    - pyregion
    - python x.x
    - setuptools
    run:
    - astropy >=1.1
    - fitsblender
    - nictools
    - numpy
    - scipy
    - stsci.convolve
    - stsci.image
    - stsci.imagemanip
    - stsci.imagestats
    - stsci.ndimage
    - stsci.skypac
    - stsci.sphere
    - stsci.stimage
    - stwcs
    - pyregion
    - setuptools
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - drizzlepac
