{% set name = 'drizzlepac' %}
{% set version = '3.1.8' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: AstroDrizzle for HST images

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - acstools
    - astropy>=3.1.2
    - astroquery
    - bokeh
    - fitsblender
    - graphviz
    - jeepney
    - lxml
    - nictools
    - nose
    - scipy
    - secretstorage [linux]
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.skypac
    - stsci.stimage
    - stwcs
    - stregion
    - setuptools
    - pandas
    - photutils
    - pysynphot
    - pypdf2
    - pytables
    - tweakwcs
    - numpy
    - python {{ python }}
    run:
    - acstools
    - astropy
    - astroquery
    - bokeh
    - fitsblender
    - nictools
    - nose
    - jeepney
    - lxml
    - scipy
    - secretstorage [linux]
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.skypac
    - stsci.stimage
    - stwcs
    - stregion
    - setuptools
    - pandas
    - photutils
    - pysynphot
    - pypdf2
    - pytables
    - tweakwcs
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
      - drizzlepac
