{% set name = 'astroimtools' %}
{% set version = '0.1.1' %}
{% set tag = 'v' + version %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Astronomical Image Tools

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - cython
    - matplotlib
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - cython
    - matplotlib
    - numpy
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}

test:
    commands:
    - imarith --help
    - imstats --help
    imports:
    - astroimtools
