{% set name = 'astroimtools' %}
{% set version = '0.2' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Astronomical Image Tools

build:
    number: {{ number }}
    skip: True [py27]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - photutils
    - astropy >=3.1
    - matplotlib >=1.3
    - scipy >=0.16
    - numpy {{ numpy }}
    - setuptools
    - python {{ python }}
    run:
    - photutils
    - astropy >=3.1
    - matplotlib >=1.3
    - scipy >=0.16
    - numpy
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}

test:
    commands:
    - imarith --help
    - imstats --help
    imports:
    - astroimtools
