{% set name = 'wfpc2tools' %}
{% set version = '1.0.3' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Tools for use with WFPC2 (Wide Field and Planetary Camera 2)

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - scipy
    - stsci.distutils
    - stsci.imagestats
    - stsci.tools
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - scipy
    - stsci.imagestats
    - stsci.tools
    - numpy
    - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - wfpc2tools
