{% set name = 'stsci-data-analysis' %}
{% set version = '4.0.0' %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu
    license: BSD
    summary: stsci-data-analysis meta-package

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - numpy {{ numpy }}
      - python {{ python }}

    run:
      - asdf >=2.5.2
      - astroimtools >=0.2
      - da5-notebooks >=1.0.0
      - jdat_notebooks >=0.1.0
      - ginga >=3.0.1
      - gwcs >=0.13
      - photutils >=0.7.2
      - imexam >=0.9.1
      - specutils >=1.0
      - spherical-geometry >=1.2.18
      - stginga >=1.1
      - tweakwcs >=0.6.1
      - webbpsf >=0.9.0
      - python
