{% set name = 'cfitsio' %}
{% set version = '3.470' %}
{% set version_short = '3470' %}
{% set number = '1' %}

about:
    home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
    license: BSD-like
    summary: CFITSIO is a library of C and Fortran subroutines for reading and
            writing data files in FITS (Flexible Image Transport System)
            data format

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - gcc_linux-64 [linux]
      - bzip2

    run:
      - libgcc >=4.7
      - bzip2

source:
    fn: {{ name }}{{ version_short }}.tar.gz
    url: http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.47.tar.gz
    #md5: 8c9b3383752f1bd663b936c297f19feb # verification broken in conda-build through 3.7.1
