{% set name = 'cfitsio' %}
{% set version = '3.430' %}
{% set version_short = '3430' %}
{% set number = '1' %}

about:
    home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
    license: BSD-like
    summary: CFITSIO is a library of C and Fortran subroutines for reading and
            writing data files in FITS (Flexible Image Transport System)
            data format

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - curl
      - gcc [osx]

    run:
      - curl
      - libgcc [osx]

source:
    fn: {{ name }}{{ version_short }}.tar.gz
    url: http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/{{ name }}{{ version_short }}.tar.gz
