{% set name = 'ginga' %}
{% set version = '2.6.6' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set tag = 'v' ~ version %}
{% set number = '1' %}

about:
    home: https://github.com/ejeschke/{{ name }}
    license: BSD
    summary: Astronomical data visualization

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.2
    - qtpy
    - pillow
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.2
    - qtpy
    - pillow
    - numpy
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/ejeschke/{{ name }}.git

test:
    commands:
    - ginga --help
    imports:
    - ginga
