{% set name = 'photutils' %}
{% set version = '0.4' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://github.com/astropy/{{ name }}
    license: BSD
    summary: An Astropy package for photometry

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=2.0
    - cython
    - matplotlib >=1.3
    - numpy >=1.9
    - scikit-image >=0.11
    - scikit-learn >=0.18
    - scipy >=0.16
    - six
    - setuptools
    - python {{ python }}
    run:
    - astropy >=2.0
    - cython
    - matplotlib >=1.3
    - numpy >=1.9
    - scikit-image >=0.11
    - scikit-learn >=0.18
    - scipy >=0.16
    - six
    - setuptools
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/astropy/{{ name }}.git

test:
    imports:
    - photutils
