{% set name = 'photutils' %}
{% set version = '0.3' %}
{% set tag = 'v' + version %}
{% set number = '2' %}

about:
    home: https://github.com/astropy/{{ name }}
    license: BSD
    summary: An Astropy package for photometry

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - cython
    - matplotlib
    - numpy
    - scikit-image
    - scipy
    - setuptools
    - python x.x
    run:
    - astropy >=1.1
    - cython
    - matplotlib
    - numpy
    - scikit-image
    - scipy
    - setuptools
    - python x.x

source:
    git_tag: {{ tag }}
    git_url: https://github.com/astropy/{{ name }}.git

test:
    imports:
    - photutils
