{% set name = 'jwst_gtvt' %}
{% set version = '0.1.0' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Calculates the allowed position angle for a given Right Ascension and
        Declination for each instrument.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - matplotlib
    - numpy {{ numpy }}
    - setuptools
    - python {{ python }}

    run:
    - astropy
    - matplotlib
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
