{% set reponame = 'stsynphot_refactor' %}
{% set name = 'stsynphot' %}
{% set version = '0.1' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ reponame }}
    license: BSD
    summary: Synthetic photometry using Astropy for HST and JWST

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - synphot >=0.1
    - astropy >=1.3
    - scipy >=0.14
    - numpy {{ numpy }}
    - pytest
    - setuptools
    - python {{ python }}

    run:
    - synphot >=0.1
    - astropy >=1.3
    - scipy >=0.14
    - numpy
    - pytest
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ reponame }}.git

test:
    imports:
    - stsynphot
