{% set name = 'astropy-healpix' %}
{% set version = '0.3.1' %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
  home: http://astropy-healpix.readthedocs.io/
  license: BSD
  summary: A Python package for HEALPix

build:
  number: {{ number }}

package:
  name: {{ name }}
  version: {{ version }}

requirements:
  build:
    - astropy
    - cython
    - setuptools <38.5.1 [(py2k or py35 or py36) and osx]
    - setuptools [(py37 and osx) or linux]
    - numpy {{ numpy }}
    - python {{ python }}

  run:
    - astropy
    - numpy
    - python

source:
  git_tag: {{ tag }}
  git_url: https://github.com/astropy/{{ name }}.git

test:
  imports:
    - astropy_healpix
