{% set name = 'costools' %}
{% set version = '1.2.3' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Tools for COS (Cosmic Origins Spectrograph)

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - astropy >=1.1
    - calcos
    - stsci.tools
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - calcos
    - stsci.tools
    - setuptools
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - timefilter --help
    imports:
    - costools
