{% set name = 'glue-vispy-viewers' %}
{% set version = '0.7.1' %}
{% set number = '1' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/{{ name }}-{{ version }}.tar.gz
  md5: 2189493a5070024ff3c412307a6a5a7e

build:
  number: {{ number }}
  preserve_egg_dir: True

requirements:
    build:
      - astropy
      - glueviz >=0.10
      - scikit-image
      - qtpy
      - python x.x
      - setuptools

    run:
      - astropy
      - numpy
      - pyopengl
      - glueviz >=0.10
      - scikit-image
      - matplotlib
      - qtpy
      - pyqt
      - python x.x

      # Temporary: the scikit-image conda package is missing the dask dependency
      # so we add it here for now
      - dask

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  summary: 3D viewers for Glue
