{% set name = 'imexam' %}
{% set version = '0.9.1' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Designed to be a lightweight library which enables users to explore
        data from a command line interface, through a Jupyter notebook or
        through a Jupyter console. It can be used with multiple viewers,
        such as DS9 or Ginga, or without a viewer as a simple library to make
        plots and grab quick photometry information.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - cython
    - setuptools
    - setuptools_scm
    - python {{ python }}
    run:
    - astropy >=3.0
    - cython
    - ginga
    - photutils
    - matplotlib
    - scipy >=0.18
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - imexam
