{% set name = 'cubeviz' %}
{% set version = '0.2.1' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Data analysis package for cubes.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - asdf
    - asteval
    - astropy
    - glue-core >=0.13
    - numpy {{ numpy }}
    - pytest
    - setuptools
    - python {{ python }}

    run:
    - asdf
    - asteval
    - astropy
    - glue-core >=0.13
    - numpy
    - pytest
    - specviz <0.6.0
    - spectral-cube >=0.4.2
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - cubeviz
