{% set name = 'stsci.ndimage' %}
{% set version = '0.10.1' %}
{% set number = '3' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Various functions for multi-dimensional image processing
        --fork of scipy.ndimage

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - stsci.distutils
    - setuptools
    - astropy >=1.1
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - numpy
    - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.ndimage
