{% set name = 'asv' %}
{% set version = '0.1.1' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set tag = 'v' + version %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        A simple Python history benchmarking tool

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - six
    - sphinx
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - six
    - sphinx
    - numpy
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
