{% set name = 'sphinxcontrib-programoutput' %}
{% set version = '0.8' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: https://pypi.python.org/packages/source/s/{{ name }}
    license: BSD
    summary: |
        Sphinx extension to include program output

build:
    number: {{ number }}
    preserve_egg_dir: True

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - sphinx
    - setuptools
    - python {{ python }}
    run:
    - sphinx
    - python

source:
    fn: {{ name }}-{{ version }}.tar.gz
    md5: bb0be17ef13f268378b2af51ff413c58
    url: https://pypi.python.org/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
