{% set name = 'spectral-cube' %}
{% set version = '0.4.3' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/radio-astro-tools/{{ name }}
    license: BSD
    summary: Library for reading and analyzing astrophysical spectral data cubes

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy
    - numpy {{ numpy }}
    - radio-beam
    - setuptools
    - python {{ python }}

    run:
    - astropy
    - numpy
    - radio-beam
    - setuptools
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/radio-astro-tools/{{ name }}.git

test:
    imports:
    - spectral_cube
