{% set name = 'asdf' %}
{% set version = '1.3.1' %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: ASDF (Advanced Scientific Data Format) is a next generation interchange format for scientific data

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - semantic_version >=2.3.1
    - astropy >=1.3
    - pyyaml
    - jsonschema
    - pytest
    - six
    - setuptools
    - numpy
    - python x.x
    run:
    - semantic_version >=2.3.1
    - astropy >=1.3
    - pyyaml
    - jsonschema
    - pytest
    - six
    - setuptools
    - numpy
    - python x.x

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - asdftool --help
    imports:
    - asdf
