{% set name = 'asdf' %}
{% set version = '2.7.0' %}
{% set number = '0' %}

about:
    home: https://github.com/asdf-format/{{ name }}
    license: BSD
    summary: ASDF (Advanced Scientific Data Format) is a next generation interchange format for scientific data

build:
    number: {{ number }}
    skip: True [py27]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - semantic_version >=2.8
    - pyyaml >=3.10
    - jsonschema >=3.0.2,<4.0
    - setuptools
    - setuptools_scm
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - semantic_version >=2.8
    - pyyaml >=3.10
    - jsonschema >=3.0.2,<4.0
    - pytest
    - setuptools
    - setuptools_scm
    - numpy
    - python

source:
  git_tag: {{ version }}
  git_url: https://github.com/asdf-format/{{ name }}.git

test:
    commands:
    - asdftool --help
    imports:
    - asdf
