{% set name = 'asdf' %}
{% set version = '2.3.2' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: ASDF (Advanced Scientific Data Format) is a next generation interchange format for scientific data

build:
    number: {{ number }}
    skip: True [py27]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - semantic_version >=2.3.1
    - pyyaml >=3.10
    - jsonschema >=2.3,<=2.6
    - six >=1.9.0
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - semantic_version >=2.3.1
    - pyyaml >=3.10
    - jsonschema >=2.3,<=2.6
    - pytest
    - six >=1.9.0
    - setuptools
    - numpy
    - python

source:
  git_tag: {{ version }}
  git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    commands:
    - asdftool --help
    imports:
    - asdf
