{% set name = 'crds' %}
{% set version = '7.2.9' %}
{% set number = '1' %}

about:
    home: http://www.stsci.edu/hst/observatory/crds/
    license: AURA
    summary: |
        CRDS assigns calibration references to data using formal rules
        represented in simple text files

build:
    number: {{ number }}
    preserve_egg_dir: 'no'
    skip: True [py2k]

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - cfitsio >=3.440
    - numpy {{ numpy }}
    - requests
    - lxml
    - parsley
    - filelock
    - setuptools
    - python {{ python }}

    run:
    - astropy >=1.1
    - cfitsio
    - numpy
    - requests
    - lxml
    - fitsverify
    - parsley
    - filelock
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - crds
