{% set name = 'acstools' %}
{% set version = '2.1.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Python tools for analyzing ACS data
build:
    number: {{ number }}
package:
    name: {{ name }}
    version: {{ version }}
requirements:
    build:
    - astropy >=1.1
    - stsci.tools
    - numpy {{ numpy }}
    - setuptools
    - python {{ python }}
    run:
    - astropy >=1.1
    - scikit-image
    - stsci.tools
    - matplotlib
    - numpy
    - python
source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
test:
    commands:
    - acs_destripe --help
    - acs_destripe_plus --help
    imports:
    - acstools
