{% set name = 'webbpsf' %}
{% set version = '0.6.0' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set tag = 'v' + version %}
{% set number = '1' %}

about:
    home: https://webbpsf.readthedocs.io
    license: BSD
    summary: |
        Creates simulated point spread functions for the James Webb Space Telescope

build:
    number: {{ number }}
    preserve_egg_dir: 'True'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - numpy {{ numpy }}
    - scipy
    - matplotlib
    - poppy >=0.6.1
    - six [py27]
    - webbpsf-data ==0.6.0
    - setuptools
    - python {{ python }}
    - ipywidgets
    - jwxml
    run:
    - astropy >=1.1
    - numpy
    - scipy
    - matplotlib
    - poppy >=0.6.1
    - six [py27]
    - webbpsf-data ==0.6.0
    - setuptools
    - python
    - ipywidgets
    - jwxml

source:
    git_tag: {{ tag }}
    git_url: https://github.com/mperrin/webbpsf

test:
    commands:
    - WEBBPSF_PATH=$PREFIX/share/webbpsf-data python -c 'import webbpsf'
