{% set name = 'pyobjc-core' %}
{% set version = '3.1.1' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: http://pyobjc.sourceforge.net/
    license: MIT
    summary: Python<->ObjC Interoperability Module

build:
    skip: True [not osx]
    number: {{ number }}
    preserve_egg_dir: 'true'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - python {{ python }}
    run:
    - python

source:
    fn: pyobjc-{{ version }}.tar.gz
    url: https://bitbucket.org/ronaldoussoren/pyobjc/get/pyobjc-{{ version }}.tar.bz2

test:
    imports:
    - PyObjCTools
    - objc
