{% set name = 'stsci.sphinxext' %}
{% set version = '1.2.2' %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: A set of tools and templates to customize Sphinx for use in STScI projects

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - numpydoc
    - stsci.distutils
    - setuptools
    - python {{ python }}
    run:
    - numpydoc
    - stsci.distutils
    - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.sphinxext
