{% set name = 'stginga' %}
{% set version = '0.3' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set tag = version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Ginga products specific to STScI data analysis

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - ginga >=2.7
    - astropy >=2
    - numpy {{ numpy }}
    - scipy
    - setuptools
    - python {{ python }}
    run:
    - ginga >=2.7
    - astropy >=2
    - numpy
    - scipy
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stginga
