{% set name = 'jwst_footprints' %}
{% set version = '2.2.0' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/jwst_coronagraph_visibility
    license: BSD-3-Clause
    summary: Visualize approximate pointing constraints for JWST coronagraphs.

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

requirements:
    build:
    - astropy >=1.3
    - matplotlib
    - numpy
    - pillow
    - pyds9
    - scipy
    - tk
    - setuptools
    - python x.x

    run:
    - astropy >=1.3
    - matplotlib
    - numpy
    - scipy
    - pillow
    - pyds9
    - tk
    - python x.x

test:
   imports:
   - jwst_footprints
