{% set name = 'jwxml' %}
{% set version = '0.3.0' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: https://github.com/mperrin/{{ name }}
    license: BSD
    summary: |
        Parse and manipulate XML files, mostly JWST optics and wavefront sensing related.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - numpy {{ numpy }}
    - matplotlib
    - python {{ python }}
    run:
    - numpy
    - matplotlib
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/mperrin/{{ name }}.git

test:
    commands:
    - python -c 'from jwxml.siaf import SIAF; SIAF(instr="NIRCam")'
